--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2025.1.134.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 2026. 05. 11. 9:03:51
-- Server version: 8.0.42
--

SET NAMES 'utf8';
