--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2025.1.134.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 2026. 05. 18. 8:35:27
-- Server version: 8.0.42
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE telekinaplo;

--
-- Drop table `idezet`
--
DROP TABLE IF EXISTS idezet;

--
-- Drop table `csoport_osszekoto`
--
DROP TABLE IF EXISTS csoport_osszekoto;

--
-- Drop table `csoport`
--
DROP TABLE IF EXISTS csoport;

--
-- Drop table `ertesites_osszekoto`
--
DROP TABLE IF EXISTS ertesites_osszekoto;

--
-- Drop table `ertesites`
--
DROP TABLE IF EXISTS ertesites;

--
-- Drop table `felhasznalo`
--
DROP TABLE IF EXISTS felhasznalo;

--
-- Drop table `szerep`
--
DROP TABLE IF EXISTS szerep;

--
-- Set default database
--
USE telekinaplo;

--
-- Create table `szerep`
--
CREATE TABLE szerep (
  id bigint NOT NULL,
  nev varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `nev` on table `szerep`
--
ALTER TABLE szerep
ADD UNIQUE INDEX nev (nev);

--
-- Create table `felhasznalo`
--
CREATE TABLE felhasznalo (
  id bigint NOT NULL,
  nev varchar(255) DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  telefonszam varchar(50) DEFAULT NULL,
  jelszo varchar(255) DEFAULT NULL,
  szerep_id bigint DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `email` on table `felhasznalo`
--
ALTER TABLE felhasznalo
ADD UNIQUE INDEX email (email);

--
-- Create index `telefonszam` on table `felhasznalo`
--
ALTER TABLE felhasznalo
ADD UNIQUE INDEX telefonszam (telefonszam);

--
-- Create foreign key
--
ALTER TABLE felhasznalo
ADD CONSTRAINT fk_felhasznalo_szerep FOREIGN KEY (szerep_id)
REFERENCES szerep (id);

--
-- Create table `ertesites`
--
CREATE TABLE ertesites (
  id bigint NOT NULL,
  esemeny_kezdo_datum timestamp NULL DEFAULT NULL,
  esemeny_vegzes_datum timestamp NULL DEFAULT NULL,
  kuldes_datum timestamp NULL DEFAULT NULL,
  cim varchar(255) DEFAULT NULL,
  leiras text DEFAULT NULL,
  felado_id bigint DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `ertesites_osszekoto`
--
CREATE TABLE ertesites_osszekoto (
  id bigint NOT NULL,
  felhasznalo_id bigint DEFAULT NULL,
  ertesites_id bigint DEFAULT NULL,
  latta_e tinyint(1) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE ertesites_osszekoto
ADD CONSTRAINT fk_ertesites_osszekoto_ertesites FOREIGN KEY (ertesites_id)
REFERENCES ertesites (id);

--
-- Create foreign key
--
ALTER TABLE ertesites_osszekoto
ADD CONSTRAINT fk_ertesites_osszekoto_felhasznalo FOREIGN KEY (felhasznalo_id)
REFERENCES felhasznalo (id);

--
-- Create table `csoport`
--
CREATE TABLE csoport (
  id bigint NOT NULL,
  csoportnev varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `csoportnev` on table `csoport`
--
ALTER TABLE csoport
ADD UNIQUE INDEX csoportnev (csoportnev);

--
-- Create table `csoport_osszekoto`
--
CREATE TABLE csoport_osszekoto (
  id bigint NOT NULL,
  csoport_id bigint DEFAULT NULL,
  felhasznalo_id bigint DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE csoport_osszekoto
ADD CONSTRAINT fk_csoport_osszekoto_csoport FOREIGN KEY (csoport_id)
REFERENCES csoport (id);

--
-- Create foreign key
--
ALTER TABLE csoport_osszekoto
ADD CONSTRAINT fk_csoport_osszekoto_felhasznalo FOREIGN KEY (felhasznalo_id)
REFERENCES felhasznalo (id);

--
-- Create table `idezet`
--
CREATE TABLE idezet (
  id int NOT NULL,
  szerzo varchar(255) DEFAULT NULL,
  idezet varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci,
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table szerep
--
INSERT INTO szerep(id, nev) VALUES
(1, 'pelda');

-- 
-- Dumping data for table ertesites
--
INSERT INTO ertesites(id, esemeny_kezdo_datum, esemeny_vegzes_datum, kuldes_datum, cim, leiras, felado_id) VALUES
(1, '2020-05-18 00:00:00', '2020-05-18 00:00:00', '2019-05-18 00:00:00', 'Pelda', 'Pelda', 1);

-- 
-- Dumping data for table felhasznalo
--
INSERT INTO felhasznalo(id, nev, email, telefonszam, jelszo, szerep_id) VALUES
(1, 'Pelda Peti', 'peldapeti@gmail.com', '36301234567', 'Peldapeti1234', NULL);

-- 
-- Dumping data for table csoport
--
INSERT INTO csoport(id, csoportnev) VALUES
(1, 'tanar');

-- 
-- Dumping data for table idezet
--
INSERT INTO idezet(id, szerzo, idezet) VALUES
(1, 'Arany Janos', 'Novella elemzést vártál... Most tövig szoptad a tölgyfám');

-- 
-- Dumping data for table ertesites_osszekoto
--
INSERT INTO ertesites_osszekoto(id, felhasznalo_id, ertesites_id, latta_e) VALUES
(1, 1, 1, 0);

-- 
-- Dumping data for table csoport_osszekoto
--
INSERT INTO csoport_osszekoto(id, csoport_id, felhasznalo_id) VALUES
(1, 1, 1);

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;